### ISSUE TITLE
font-awesome

### ISSUE THREAD

**Issue by xcodebuild** [7sDream/moon-render#1]
https://fontawesome.com/icons/github-alt?style=brands

![image](https://user-images.githubusercontent.com/5436704/72091230-a827d280-334a-11ea-8e5d-2dc898995dd1.png)

https://fontawesome.com/icons/github?style=brands

![image](https://user-images.githubusercontent.com/5436704/72091245-ad851d00-334a-11ea-94db-faedbc53ba6e.png)

**Comment by 7sDream** [comment]
Great! 

But I notice a but in the first render result: the eye in right side has stick to head outline.

Will try to fix it.

**Comment by 7sDream** [comment]
![](https://rikka.7sdre.am/files/22a7b2b3-7b52-4834-a3cd-9eaae67f51f2.png)

![](https://rikka.7sdre.am/files/0a8414a4-59e6-433c-8f54-e1c60d4dafd2.png)

Result from new render policy.

Will add thoose great and attractive examples to README.
